# Generated by Django 4.2.2 on 2023-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_app', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.ManyToManyField(to='news_aggregator_app.category', verbose_name='categories'),
        ),
    ]
