# Generated by Django 4.2.2 on 2023-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_app', '0003_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='news_aggregator_app.category', verbose_name='category'),
        ),
    ]
