# Generated by Django 4.2.2 on 2023-06-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_app', '0004_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.URLField(max_length=400, verbose_name='image'),
        ),
    ]
